### ISSUE TITLE
[Suggestion] [1.12.2] Ability to allow breaking bedrock. Multi-Tool

### ISSUE THREAD

**Issue by deadspidervenom** [CJ-MC-Mods/IBHSTD#100]
I have a pack i am working on and i really like the tool, however one of the tools in my endgame (that are worse then yours) is able to break bedrock where yours cannot.

Just a config option defaulted too false is good, just would like to enable it to be of the same use as the tool.

**Comment by cjm721** [comment]
No feature work is being done for 1.12

Multi-Tool has no special code to prevent breaking of bedrock, it does everything based on hardness and the invulnerable flag. I would not add something special for one block without making it configurable for all blocks. In 1.15 there are easier ways of doing something like this that I may explore, but for now now.

In general though something being invulnerable means its only supposed to be broken by its own mod, normally for game-play or other reasons. Making something that breaks that normally just results in an escalation of them trying to find a way to prevent it (think thaumcraft warded blocks).
