### ISSUE TITLE
[Feature request] OreDictionary for compressed blocks

### ISSUE THREAD

**Issue by Monniasza** [CJ-MC-Mods/IBHSTD#101]
The compressed blocks don't have OreDictionary, so they are difficult to integrate with mods.

**Comment by cjm721** [comment]
Compressed Block is only a feature in 1.12 or lower Overloaded, it was split it its own mod for higher versions.

**Comment by Monniasza** [comment]
@cjm721 This issue affects Overloaded for Minecraft 1.12.2
