### ISSUE TITLE
How to use the railgun?

### ISSUE THREAD

**Issue by farnoods** [CJ-MC-Mods/IBHSTD#102]
What are the names of control options that allow you to change modes and fire the railgun? I can't find any information on this online. And also in the in-game controls menu, there is only one button under Overloaded and that controls something about the armor and doesn't work with the railgun

**Comment by braingkk** [comment]
right click shoots, and some combination of something+scrollwheel to change power draw

**Comment by farnoods** [comment]
does it need some sort of ammunition?

**Comment by braingkk** [comment]
Forge energy units, can be filled in item interface or most modded charging blocks

**Comment by braingkk** [comment]
Closing the issue, assuming your questions have been answered. 

Please follow the issue format if you have questions/issues in the future, as mod/minecraft versions are sometimes relevant when a mod exists for several versions of minecraft and has changed in some ways over the years.
