### ISSUE TITLE
compatible issue with Overloaded and simplestoragenetwork 

### ISSUE THREAD

**Issue by IchigoGames** [CJ-MC-Mods/IBHSTD#103]
#### Overloaded Version: Overloaded-1.16.3-0.0.90
jei-1.16.4-7.6.0.58 tested both jei-1.16.3-7.6.0.51
SimpleStorageNetwork-1.16.3-1.2.0 also tested SimpleStorageNetwork-1.16.3-1.3.0

Single player or Server:both

this is a issue with overloaded and simplestoragenetworks a compatible issue with the two mods that messed up the text rendering on the storage interface this happens in 1.16.3 and in 1.16.4

video https://www.youtube.com/watch?v=4DqTqrp1cFk&ab_channel=IchigoGames
log https://www.dropbox.com/s/jdv8socnxhygmf6/latest.log?dl=0

https://github.com/Lothrazar/Storage-Network/issues/321

**Comment by cjm721** [comment]
Went through all the things I thought it could be: resource packs, langauge keys, etc. All of them are mapped correctly so don't know what is causing this.

**Comment by IchigoGames** [comment]
ok well thanks that mod then the other mod dev had  done i ended up removing simplestoragenetworks you can close this if you want.
