### ISSUE TITLE
How do you use Infinity Storage? The wiki doesn't explain it very well

### ISSUE THREAD

**Issue by aaronhowser1** [CJ-MC-Mods/IBHSTD#108]
So the Almost Infinity Barrel can hold the maximum possible according to Java. Same with Tank and Capacitor.

Does the True Infinity Barrel/Tank/Capacitor just give an infinite amount of the items? How do you set them? Right-clicking with an item doesn't do anything.

The Hyper Transfer page says it has something to do with Hyper Item Receivers and Senders, but what about them? I've linked two, but pipes of all kind (including hoppers) don't seem to do anything.

**Comment by cjm721** [comment]
Almost Infinity only holds 2^63, True Infinity are the ones that go to java limit. They are normal storage, and do not generate items.

Hyper X only works with the Infinity storage blocks and when they are directly next to them.

**Comment by aaronhowser1** [comment]
So you place the Hyper Item Inserter next to the True Infinity Barrel, and then what? You can't insert items into the Inserter.

What does linking do, if they both have to be next to the barrel? Can you remotely remove items, but not insert them? Other way around?
