### ISSUE TITLE
Crash when leaving a clickmachine running during server startup

### ISSUE THREAD

**Issue by DragarX** [CJ-MC-Mods/IBHSTD#112]
#### Overloaded Version: <Replace>

I have a mob grinder setup with a click machine as the damage dealer, whenever I leave it on and close the game, the next time I load in overloaded causes the game to crash. Is there any way you can ignore the click machine when checking for client side events.

[crash-2022-01-30_12.48.41-server.txt](https://github.com/CJ-MC-Mods/Overloaded/files/7965143/crash-2022-01-30_12.48.41-server.txt)

**Comment by cjm721** [comment]
Will add some defensive code on my side but would also report this to ClickMachine as shouldn't be firing an entity event with no entity.
