### ISSUE TITLE
Multi armor model issue in the Age of Fate modpack 

### ISSUE THREAD

**Issue by OutFang** [CJ-MC-Mods/IBHSTD#116]
#### Overloaded Version: 0.0.96

Hello , 
I recently started playing on the Age of Fate modpack , which has overloaded in it , and managed to craft the multi armor . 
The problem is that when i put it on i'm okay but as soon as I try to go in 3rd person or in my inventory to see the armor , the game crashes saying :

Description: Rendering entity in world

java.lang.IllegalStateException: BufferBuilder not started

Here is the pastebin link to my crash file :
https://pastebin.com/5N7tmKEC

Thanks for your help !

**Comment by cjm721** [comment]
It wasn't Overloaded Armor. Was an Armor Stand
```
-- Entity being rendered --
Details:
	Entity Type: minecraft:armor_stand (net.minecraft.entity.item.ArmorStandEntity)
	Entity ID: 2373
	Entity Name: Armor Stand
	Entity's Exact location: 5687.50, 188.00, -3469.50
	Entity's Block location: World: (5687,188,-3470), Chunk: (at 7,11,2 in 355,-217; contains blocks 5680,0,-3472 to 5695,255,-3457), Region: (11,-7; contains chunks 352,-224 to 383,-193, blocks 5632,0,-3584 to 6143,255,-3073)
	Entity's Momentum: 0.00, -0.13, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
 
-- Renderer details --
Details:
	Assigned renderer: net.minecraft.client.renderer.entity.ArmorStandRenderer@6cfa9657
	Location: -1.82,-1.62,0.42 - World: (-2,-2,0), Chunk: (at 14,-1,0 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Rotation: -90.0
	Delta: 0.82006836
```

From that guess it is something from me.jellysquid.mods.sodium as only mod in the stack trace

**Comment by OutFang** [comment]
The problem is that the armor stand won't render because the multi armor helmet is on it . 
I crafted the multi armor and everything was fine as long as it wasn't on me or on the armor stand , thats why i said the " multi armor model" . 

Here is an other crash from when it was on my character : 
https://pastebin.com/yXgv4WmL

sorry to disturb you and thanks again for your help

**Comment by braingkk** [comment]
looks like rubidium doesnt like the "multiArmorFancyModel" set to true. go to overloaded-client.toml and change it to false. should hopefully fix it for now. We will look into it more, but figured I would give you a temp fix for your world

**Comment by cjm721** [comment]
Fancy armor option is set to default false as it doesn't look right currently anyways. It does a lot of custom rendering so doesn't surprise me Rubidium (Sodium clone / fork) breaks it.
