### ISSUE TITLE
Overloaded Fluid - Pure Matter

### ISSUE THREAD

**Issue by Kirbyarm** [CJ-MC-Mods/IBHSTD#120]
This is using one of the 1.12.2 versions of the mod in a modpack. I'm seeing this fluid in JEI, and it looks beautiful for potential decorative purposes, but I can't find any trace of how to obtain this liquid either in game or via extensive Google / YouTube research. Can you please tell me how to get this stuff?

**Comment by cjm721** [comment]
Acquisition is not implemented.
