### ISSUE TITLE
[Question][Convenience] Block breaking speed in 1.12

### ISSUE THREAD

**Issue by accessdenied0** [CJ-MC-Mods/IBHSTD#20]
#### Overloaded Version: 0.0.26

I know this is just a convenience addition but I noticed on breaking a Infinity Watersource that, even it doesn't need a tool, the block breaking took extremely long. Could you maybe change it to a _"nearly instant but not instant breaking"_ speed?

In addition: is it possible to make the Infinity Watersource to push the water out at default?

access_denied

**Comment by cjm721** [comment]
I will not make the infinite water source push water.  The point is to have as little ticking time entities as possible.  

As for making it require a tool I will think about it.

**Comment by accessdenied0** [comment]
I do not want for it to require a tool... My question was to reduce the time it takes to break a block... <.<

And if the watersource doesn't push the water I need a ticking tile entity to pull it out, am I wrong? In the worst case I have 1 watersource with 6 ticking tiles on it... (I know it is unlikely but hey who knows)
I respect your decision on the first one but the last one wasn't my request.

**Comment by cjm721** [comment]
The source would not know when it needs to push nor which side so it would always have to check all 6, while with external pipes you only need one ticking and it only needs to tick when it needs to pull. Also if you are using more then one side of the source for the same task use better pipes.
