### ISSUE TITLE
Server crash with ore excavation overloaded and ex2

### ISSUE THREAD

**Issue by tyler489** [CJ-MC-Mods/IBHSTD#21]
#### Overloaded Version: <Replace> 0.0.26
Seems that ```        float chance = event.getDropChance();
        for(ItemStack stack: event.getDrops()) {
            if (world.rand.nextFloat() <= chance) {
                EntityItem toSpawn = new EntityItem(world, player.posX, player.posY, player.posZ, stack);
                world.spawnEntity(toSpawn);``` is being called both by overloaded and by ore excavation. Although i could be wrong  https://pastebin.com/3d4iZAtx

**Comment by tyler489** [comment]
A work around might be to get item position and compair it to player position if its the same the cancel the item spawn event?

**Comment by cjm721** [comment]
Ended up being from ExU2 using an Immutable List, Only crashed because using sponge.

I have added some code as a work around but ExU2 should not be using Immutable List for HarvestDropEvents
