### ISSUE TITLE
Instant Power drain

### ISSUE THREAD

**Issue by tyler489** [CJ-MC-Mods/IBHSTD#22]
#### Overloaded Version: <Replace>Newest
Shift equiping armor instantly drains the entire charge of the armor

**Comment by cjm721** [comment]
Newest is not a helpful version definition.

Also I was not able to replicate it.

**Comment by tyler489** [comment]
Overloaded-1.12-0.0.28.jar

http://youtu.be/zknEy7oOKNg?hd=1

**Comment by cjm721** [comment]
Tried it on the BTNF pack and did not happen to me. So you have to have something else that is also effecting it that I could not see from the video.

Where you in a morph? Also what does your config look like.

**Comment by cjm721** [comment]
Forgot to close this. The issue was a sponge plugin setting saturation to around negative int max.
