### ISSUE TITLE
[1.12] Energy Extractor Recipe Conflict with Tesla Battery

### ISSUE THREAD

**Issue by Morpheus1101** [CJ-MC-Mods/IBHSTD#23]
#### Overloaded Version: 0.0.29

As per discussion on Discord the recipe for the Energy Extractor is the same as the Tesla Battery from TeslaCore Lib of which mod overrides the recipe in Overloaded.

**Comment by cjm721** [comment]
Changed Recipe to require two Redstone blocks.
