### ISSUE TITLE
crashing in loading screen

### ISSUE THREAD

**Issue by IchigoGames** [CJ-MC-Mods/IBHSTD#27]
#### Overloaded Version: Overloaded-1.12.1-0.0.34
crashs in loading screen crash report https://pastebin.com/ywz655ZL

**Comment by IchigoGames** [comment]
found out more info it only happens with you use a resource pack your compressed blocks has some issue with spax not sure if it also happens with other resource packs

**Comment by cjm721** [comment]
The issue was with having compressed blocks with animated textures. Just using the first image if it is animated now.
