### ISSUE TITLE
1.12 Still seeing no compressed blocks

### ISSUE THREAD

**Issue by Zygus42** [CJ-MC-Mods/IBHSTD#28]
Minecraft Version: forge-1.12.1-14.22.0.2457-installer-win
Overloaded Version: Overloaded-1.12.1-0.0.35.jar

The changelogs keep talking about improvements to the compressed blocks, but JEI shows no compressed blocks in the mod.

**Comment by cjm721** [comment]
You have to set the blocks you want compressed in the config.
