### ISSUE TITLE
Cant "un"craft 1x compressed back to original blocks

### ISSUE THREAD

**Issue by OrdinatorStouff** [CJ-MC-Mods/IBHSTD#30]
#### Overloaded Version: Overloaded-1.12.1-0.0.41.jar

Compressed blocks recipe back into normal/original/base blocks is not working. For example the following compressed.json:
```json
[
  {
    "baseRegistryName": "minecraft:obsidian",
    "compressedPathRegistryName": "compressed_obsidian",
    "meta": 0,
    "texturePath": "minecraft:textures/blocks/obsidian.png",
    "depth": 4,
    "hardnessMultiplier": 2.0,
    "recipeEnabled": true
  }
]
```
registers compressed obsidian blocks and 9x vanilla obsidian can be crafted into 1x compressed but 1x compressed can not be crafted back to vanilla obsidian. JEI shows that it is a recipe, but in personal 2x2, vanilla crafting table 3x3, or a few other modded craft grids, there is no output when the 1x compressed is placed in any of the input slots

**Comment by cjm721** [comment]
Fixed in b4209c4b54117cb103cab222c4ec7565399da710
