### ISSUE TITLE
[Question] Compressed Blocks 1.10.2

### ISSUE THREAD

**Issue by Cristaltek303** [CJ-MC-Mods/IBHSTD#33]
Im currently building a modpack for 1.10.2.
Now i would like a to add a compressed version of enderio's electrical steel block.
but if i type in your config:

enderio:blockElectricalSteel:8:true 

nothing is happening.
I think it has to do with the programming code from enderio, because i think the blockID is:

enderio:blockIngotStorage:0

now my question is: 
is it possible to specify metadata in your config option for compressed blocks?

**Comment by cjm721** [comment]
Metadata is not supported in old versions. I added that in 1.12 and currently do not plan to backdate that system.
