### ISSUE TITLE
Can't enter flight in no-clip mode

### ISSUE THREAD

**Issue by ouroborus** [CJ-MC-Mods/IBHSTD#34]
#### Overloaded Version: 1.12.1-0.0.44

If you aren't in flight mode when entering no-clip clip, you can't enable flight. If you are in flight mode when enter no-clip, you can exit and enter flight as normal.

Perhaps making it so no-clip automatically forces flight?

**Comment by cjm721** [comment]
That is a vanilla issue. It is on my todo list to code some way around it (or just make flying enable when you enter noclip, which is what vanilla does). As it is nice to be able to fall through fast so I am hesitant to just go with the on by default.
