### ISSUE TITLE
Enchantment textures seem broken

### ISSUE THREAD

**Issue by ouroborus** [CJ-MC-Mods/IBHSTD#35]
#### Overloaded Version: 1.12.1-0.0.44

Enchantment textures do not appear as they normally do. 

Short video of effect: https://youtu.be/62hVuGhxuHk

**Comment by cjm721** [comment]
My rendering code is based on brandon's work and he has not figured out what is causing that either. For time being just going to make it so no enchant glint will attempt to render on my items. When brandon figures out how to fix his then I will copy it over as well.
