### ISSUE TITLE
Only able to enchant via anvil

### ISSUE THREAD

**Issue by ouroborus** [CJ-MC-Mods/IBHSTD#36]
#### Overloaded Version: 1.12.1-0.0.44

It seems only the vanilla anvil is capable of enchanting the armor (by way of enchantment books). The vanilla enchantment table and various mod enchantment machines either don't work or don't accept the armor. 

Any chance we could get general enchantment compatibility so that the armor can be enchanted similar to how other armor can be enchanted? 

(I know the armor makes you invulnerable so most armor enchantments are pointless. But some mods add utility enchantments like night vision and speed that are pretty useful.)

**Comment by cjm721** [comment]
Bug is actually that they aren't enchant-able at all. When in creative you can enchant anything with anything.

**Comment by ouroborus** [comment]
I wasn't in creative mode.
