### ISSUE TITLE
Crashing on Minecraft launch when 64x64, 126x126 or 256x256 textures are selected

### ISSUE THREAD

**Issue by BriGuy64** [CJ-MC-Mods/IBHSTD#37]
#### Overloaded Version: 0.0.44

I am having issues with this mod in the the All The Mods 3 mod pack, version 5.7b. The mod pack is running on forge version 14.23.1.2587. Currently I am having issues loading this pack when I use 64x64 to 256x256 textures in a resource pack. With no issues with resource packs that include 16, 32 or 512 textures. I have tried a few different 128x128 Resource packs with all having the same issue. 

Currently with this issue: I can swap to the resource pack with those textures to without too much issue; but if I try to load the game with a resource pack that uses 64, 128 or 256 textures selected, when Minecraft was closed, I will crash on the following launch with a "The game crashed whilst initializing game" with the error "java.lang.UnsupportedOperationException: This method is not supported by this color model". As part of my testing I have tried removing FomFix from the pack with no change. I have also tried adding TexFix and OptiFine one at a time with no impact on this issue. So I reviewed the crash logs and found this mod calling that java argument leading to the crash. Removing this mod from the ATM3 pack allows my MC to launch with 64, 128 and 256 textures selected. As this mod adds compressed blocks with dynamic textures that may have been the cause, I re-added the mod and tried lowering the Resolution for "texture resolutions" and "compressed blocks" in the configs with no change. 

To add to this troubleshooting, this is a new clean Windows 10 OS with java Version 8 Update 151 x64 installed. I have also downloaded the current version of ATM3 as a new instance in the Twitch Launcher to rule out a possible bad download of the mod or pack. I have tried to search this issue, and due to the mod name, it's hard to find things as results are asking if I overloaded the Minecraft instance. The oddest thing with this crash, is I have no issues loading the 512x512 resource packs. 

I have attached both the logs and crash-reports from this issue, and tried using the newest version of Overloaded.

Logs from Overloaded Version: 0.0.44
[crash-2018-01-16_20.33.11-client.txt](https://github.com/CJ-MC-Mods/Overloaded/files/1637451/crash-2018-01-16_20.33.11-client.txt)
[latest.log](https://github.com/CJ-MC-Mods/Overloaded/files/1637452/latest.log)

Logs from Overloaded Version: 0.0.45
[crash-2018-01-16_21.03.04-client.txt](https://github.com/CJ-MC-Mods/Overloaded/files/1637462/crash-2018-01-16_21.03.04-client.txt)
[latest.log](https://github.com/CJ-MC-Mods/Overloaded/files/1637465/latest.log)

**Comment by cjm721** [comment]
From looking through the crash log you are on 1.8.25 version of java. 1.8.40 greatly changed many of the UI libraries. It would not surprise me if updating java fixes your issue.

**Comment by BriGuy64** [comment]
Sorry about that, I thought I was up to date. I just updated Java to "Java Version 8 Update 161" and had the same issues. Here are the logs:

Logs from Overloaded Version: 0.0.44
[crash-2018-01-17_01.29.30-client.txt](https://github.com/CJ-MC-Mods/Overloaded/files/1637924/crash-2018-01-17_01.29.30-client.txt)
[latest.log](https://github.com/CJ-MC-Mods/Overloaded/files/1637926/latest.log)

Logs from Overloaded Version: 0.0.45
[crash-2018-01-17_01.33.10-client.txt](https://github.com/CJ-MC-Mods/Overloaded/files/1637929/crash-2018-01-17_01.33.10-client.txt)
[latest.log](https://github.com/CJ-MC-Mods/Overloaded/files/1637930/latest.log)


Edit: Wait the logs are still saying I am on Java Version: 1.8.0_25 Give me a moment to check that.

**Comment by cjm721** [comment]
Still running on java 1.8.25 twitch / Minecraft launcher uses an embed version of java, have to go into the launcher setting and change it.

**Comment by BriGuy64** [comment]
Here is a current crash from telling Twitch to use the JAR launcher using the latest Java version. 
Logs from Overloaded Version: 0.0.45
[crash-2018-01-17_01.50.57-client.txt](https://github.com/CJ-MC-Mods/Overloaded/files/1637966/crash-2018-01-17_01.50.57-client.txt)
[latest.log](https://github.com/CJ-MC-Mods/Overloaded/files/1637967/latest.log)

Java is now listed in the crash log as as "Java Version: 1.8.0_161" Which matches the "Java Version 8 Update 161" I just installed on to the system.

**Comment by cjm721** [comment]
Narrowed it down to an interaction with your texture pack. Only thing I see abnormal is that it uses 8bit pngs.
