### ISSUE TITLE
Messed up block breaking animation

### ISSUE THREAD

**Issue by Liiw** [CJ-MC-Mods/IBHSTD#38]
#### Overloaded Version: Overloaded-1.12.2-0.0.46.jar

Hello!

I had OL installed with numerous other mods in a custom pack. I noticed that the block breaking animation is different from the intended "crack" animation. Namely- it is a collection of random images from the game (items, block textures etc).  For example on the following image, there is a flame on one side and a seedling on the top side:

![image](https://user-images.githubusercontent.com/14122419/35476038-00157daa-03b2-11e8-8241-efb856729216.png)

On this image, you can see....something on the front side:

![image](https://user-images.githubusercontent.com/14122419/35476047-25e39d78-03b2-11e8-8e73-9f9f0ca32491.png)

I have also experienced brick textures and wire coils from IE. I have managed to narrow it down to Overloaded as after removing this mod, the cracking animation is normal again. Note that this is not dependent on the resource pack as it happened with vanilla textures also.

**Comment by cjm721** [comment]
What is the minimum set of mods that it is happening with, because I just launched ATM and its not happening on that pack and that has a lot of mods.

**Comment by Liiw** [comment]
I will test this in the near future and report back.

**Comment by Liiw** [comment]
I tried narrowing it down to any of the other mods in my custom pack, but I was unable to recreate the issue. Most probably a forge update fixed it. I will close the issue now. Thank you for your help!
