### ISSUE TITLE
Prevent changes in MaxHP?

### ISSUE THREAD

**Issue by ouroborus** [CJ-MC-Mods/IBHSTD#39]
While still a pretty rare thing, there are effects that reduce MaxHP. (Kikoku from Extra Utilities, planned dimensional effects from Wizardary.)

Any chance we could get a mode whereby MaxHP changes are prevented?

**Comment by cjm721** [comment]
Effect as in potion effect? The armor will automatically remove any negative potion effects every tick.

Outside of it being a potion effect I would not want to  be removing things added by other mods as that is just asking to create a buggy mess.

**Comment by ouroborus** [comment]
No, as in they knock down your MaxHP permanently in the same way that some other items permanently raise your MaxHP.

Kikoku is a sword that does normal sword stuff plus decreases the targets MaxHP. They do this to prevent things like healing, regen, and invulnerability. As you might guess, when you reach zero MaxHP, you die just as if you'd been killed in a more traditional way.

**Comment by cjm721** [comment]
On ExU2 1.7.3 Kikoku has no effect on a player wearing Multi-Armor. Also that blade was not effecting a players max health even when wearing no armor.

**Comment by ouroborus** [comment]
Hrm. Maybe was a thing in the ExUtils2 for 1.10. Closing for now. May revisit this once I see what's up with Wizardry.
