### ISSUE TITLE
what does the item interface actually do?

### ISSUE THREAD

**Issue by DoomSquirter** [CJ-MC-Mods/IBHSTD#41]
mc 1.12.2
Overloaded-1.12.2-0.0.46

read https://github.com/CJ-MC-Mods/Overloaded/wiki/Item-Interface and it says the item inside dictates what it presents itself as, but when I put a TE energy cell in there, waila shows an RF bar but it doesn't seem to connect up to power using TE/TD ducts.  just curious what it's supposed to be used for.

**Comment by cjm721** [comment]
It exposes the capabilities of an item as a tile. So anything that uses the forge capability system should work as expected it in. TE ducts last time I checked just weren't always updating visually so try to pass power through it. For how simple the system actually is if it does not behave as expected it's more likely a fault (/ miss understanding of the player of what the item does) of the item rather then my block. This is exposing some low level stuff in a generic way so it is definitely not going to work as expected with all mods.

 https://mcforge.readthedocs.io/en/latest/datastorage/capabilities/

**Comment by DoomSquirter** [comment]
ok that's neat and btw, the model looks so nice and clean.  I thought I had installed mc 2.0 or something lol.  thanks for the reply
