### ISSUE TITLE
Just a question about the player interface

### ISSUE THREAD

**Issue by GreatestFool** [CJ-MC-Mods/IBHSTD#47]
Sorry if I'm asking in the wrong place. But is it possible to remotely apply effects to a player with the player interface? So that I can for example give myself regeneration by using a potion without it actually entering my inventory?

If there isn't any way for this to be done, can something like this possibly be implemented?

**Comment by cjm721** [comment]
It depends. The player interface (along with the item interface) are actually simple in what they do but rather complex when trying to explain. They only expose the capabilities of what they are attached to (a player / an item). 

So any capability added to a player from any mod will be available from the player interface. With that I also have no plans on adding the player capability as it would not fit in with the mod currently.
