### ISSUE TITLE
(Suggestion) (Maybe for addon) Multiblock compactor

### ISSUE THREAD

**Issue by Thunder-Nova** [CJ-MC-Mods/IBHSTD#48]
#### Overloaded Version: <Replace>

I am wondering if it would be possible to make an addon to your mod, that create some blocks that can "Compact" multiblock structures.

Such as the many machines of Immersive Engineering, the tinker's construct smeltery, Thaumcraft's Infusion Altar and so on.

To avoid conflict between mods since they all update at their own pace, having them "named" compactors. Ex: Immersive Compactor, Thaumic Compactor.

For the compactor to work, either craft the compactor with the material, or place the compactor on the multiblock build and poof.

Some multiblock structures such as example the I.E. Press and Thaumcraft's Inf.Altar don't have a GUI, though could make a good way for automation.

I do love the idea of compacting, yet even though there is the compact cubes mod, it would be more beneficial, to have a mod that actually removes "active" builds and make it less stressful for the servers and single player.

**Comment by cjm721** [comment]
Everything you suggested would be add-ons to Immersive Engineering / Thaumcraft, not Overloaded. If there was a way to dynamically take any and every multiblocks and put them into a single block sure, but that is not feasible with how there is no standard way create a multiblock.

At some point I will be making furnaces / grinders / generators, but they will be Overloaded themed not based on some other mod.

**Comment by Thunder-Nova** [comment]
Understandable, I was more thinking that your mod is fitting for reducing some form of lag, so having a side mod as addon for multi-mod purposes.

But if you do manage to make a multiblock detecting block that can absorb the structure and pop out a block in it's place, it would be interesting.

Exemple: Place a block next to a smeltery, and get a Magmatic Crucible.

The modpack creators can make the results from that manually. From what I can see from your intention on your mod in which the modpack creator does have to make the endgame recipes.

**Comment by sironin** [comment]
What CJ was saying there about "no standard way create a multiblock" is that not all multiblock structures are implemented the same way in code.  So each one you wanted to compact would have to be coded separately (or get Forge to implement a standardized multiblock class of some sort).  With hundreds of multiblocks out there in the wild, that's a pretty daunting task.  Just doing all of Immersive Engineering would be brutal.  

That's basically why the compact machines mod basically just has a room you put the multiblock in out of sight instead actually having a separate single block that duplicates its functionality.  But this doesn't really do much of anything about lag other than hide it in another dimension.

**Comment by cjm721** [comment]
Adding on to sironin's statement. The only way it be possible would be to push it all on the mod pack author.  95% of what you ask for already exists through Modular Machinery (which forces the pack dev to do all the logic). The only new feature would be when the multi block is created you want it to shrink to single block / have some other way to craft it (could do via vanilla crafting through craft tweaker). Modular Machinery has an add-on that was particularly coded to support the APIs of a small set of other mods for their energy/Mana/capabilities. So could ask that add-on author to add the capabilities you want then using craft tweaker do the rest.
