### ISSUE TITLE
Infinity Tank looses more fluid than actually transfered with OC Xnet

### ISSUE THREAD

**Issue by Fatmice** [CJ-MC-Mods/IBHSTD#50]
#### Overloaded Version: Overloaded-1.12.2-0.0.53
![2018-11-15_19 07 47](https://user-images.githubusercontent.com/8956281/48591583-2f75e380-e90a-11e8-8dea-bafb680e54b7.png)
![2018-11-15_19 07 54](https://user-images.githubusercontent.com/8956281/48591584-2f75e380-e90a-11e8-814d-5667e8e56f2e.png)

OC Xnet does a test of the request to transfer fluid from source to sink with the given amount to see how much can actually be transfered into the sink.  However the given amount is simply removed from the Infinity Tank regardless of the actually amount that was ultimately transferred.

In picture, 32000 is the amount requested to be transferred from source to sink.  The actual amount transferred were 8000x2.  Thus the actually amount that should be lost from the Infinity Tank should be 16000 but 64000 was lost instead.

1,716,131,361,230 - 1,716,131,297,230 = 64000

**Comment by cjm721** [comment]
Tested locally and was not seeing at all what you where describing so was going to ask for more info. Decided to look into OCXNets code instead. 

OCXNet doesn't check how much the target container was able to take so its just deleting the excess.
