### ISSUE TITLE
Hyper Transfer wont work

### ISSUE THREAD

**Issue by GammelBro** [CJ-MC-Mods/IBHSTD#53]
#### Overloaded Version: 0.0.35

Hello I have the problem that the Hyper Transfer Energy wont work. I tried many different setups but nothing work the way I want it. Here are my setups [https://i.imgur.com/bJI4HNO.png](https://i.imgur.com/bJI4HNO.png). Can someone help me?

**Comment by braingkk** [comment]
https://github.com/CJ-MC-Mods/Overloaded/wiki/Hyper-Transfer
'they only move from one Infinity Container to another.'
that is why 1 works, but 2 and 3 do not

**Comment by cjm721** [comment]
Closing as braingkk explained how it works and there has been no response sense.
