### ISSUE TITLE
Compress Netherrack look like compress Cobblestone (Gray, not red)

### ISSUE THREAD

**Issue by Fireztonez** [CJ-MC-Mods/IBHSTD#54]
#### Overloaded Version: 0.0.53

I reallyu don't undersatnd why, but the texture of the compress Netherrack is totally wrong and look really more like Compress Cobblestone, than Netherrack...

Can you look to fix that issue, because this is really anoying bug...
![compress_ netherrack](https://user-images.githubusercontent.com/19277301/52925917-815f4880-3301-11e9-8152-baab0b4a95eb.jpg)

Thank's
Fireztonez

**Comment by cjm721** [comment]
That is something that is client side only so you can modify the overloaded/compressed.json and replace the texturename for netherrack with the correct file (netherrack.png).

Pushed commit to fix it for people who use the default ones in future builds. (That file is never updated if set so new release won't fix it for you unless you delete the file, and didn't have anything non-default in it.)

**Comment by Fireztonez** [comment]
Ok thank's @cjm721 for your fast reply and to explain me how to fix the issue :D
