### ISSUE TITLE
[FR] Make compressed blocks retain block properties?

### ISSUE THREAD

**Issue by ghost** [CJ-MC-Mods/IBHSTD#57]
#### Overloaded Version: <0.0.55>
Hello, so i was messing around with the compressed blocks but noticed that a block that would regularly be not moveable, like obsidian, would be able to be moved when in a compressed form. (8x compressed, etc) It would be great if you could make it retain its block properties, if it is possible.
Thanks!

**Comment by cjm721** [comment]
Sounded like a good idea at first so looked into it. Ended up that both Minecraft and Forge both do things that make this much more difficult then it should be.

Obsidian not being pushed by a piston is not part of Obsidian but rather pistons. For modded blocks (if following Forge's suggested guidelines) it is part of the block properties so it could be copied.

Forge does state mapping as soon as a block is registered but compressed blocks don't know the base block's custom properties at that point which end up causing issues in its state mapper (could get around but might break some comparability). Second issue is that Forge doesn't actually use the rendering state mapper I give it soon as adding the extra properties it can't find the correct model (this might not be an issue in 1.13).

So marking this as would like to but can't at least in current forge state 1.12
