### ISSUE TITLE
Gradle build failing

### ISSUE THREAD

**Issue by ghost** [CJ-MC-Mods/IBHSTD#59]
#### Overloaded Version: <0.0.5.5>
I got an error while building the code, and i did not do anything to it. Keep in mind i'm very new to this, so there might be something very obvious i did wrong. Here is the error:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Overloaded-1.12'.
> apiKey not set for project 264601

**Comment by cjm721** [comment]
Remove the curse forge setting in the build.gradle or set your own curseForgeAPIKey
