### ISSUE TITLE
Creative generator idea

### ISSUE THREAD

**Issue by ghost** [CJ-MC-Mods/IBHSTD#60]
#### Overloaded Version: <0.0.5.5>
Hello, this might be a not-so-smart idea but i was wondering if it was possible to make the Creative generator produce 2^63 - 1 rf/t instead of 2^31 - 1 rf/t? I am new to coding so this might be a stupid question, but i know you can store more than 2,147,483,647 rf, so does that mean it would be possible?

EDIT: Not saying this should be implemented in any way, was just wondering since you had a way to store a lot of RF.

**Comment by cjm721** [comment]
RF can only go to 2^31. The infinity capacitor does not store RF.
