### ISSUE TITLE
Can't find setting to disabled the item's recipe

### ISSUE THREAD

**Issue by Fireztonez** [CJ-MC-Mods/IBHSTD#64]
#### Overloaded Version: 0.0.55
Hello, I read the noticed in Curse Forge about the recipes and I totally agree, recipes are way too cheap for what it does, and for what is say, it should have possibility to disabled all item's recipes, but I can't find that settings in the configs files.

I know, I can remove all recipes using crafttweaker, but, if this is possible to disabled directly from config, this is better I think than adding and removing recipes after... So if there have that option, where can I found? Unless, I wil, just do by crafttweaker ;)

Fireztonez

**Comment by cjm721** [comment]
The compressed blocks have disable-able recipes via config. All the other items will have to use craft-tweaker (old config entries for all items work in 1.10 / 1.11)
