### ISSUE TITLE
Crash with projectex tome of knowledge

### ISSUE THREAD

**Issue by ghost** [CJ-MC-Mods/IBHSTD#65]
#### Overloaded Version: <0.0.5.5>
Hello, so i had the Tome of Knowledge from projecte and when i opened the transmutation table, my screen turned blank and i got this crash report:
https://pastebin.com/B1VrGtEg

**Comment by sironin** [comment]
Can you replicate without Optifine?  It can be difficult to tackle non-optifine rendering crashes when it is active.

For reference the Developer is on a business trip at the moment and may take a week to respond.
