### ISSUE TITLE
[Suggestion] Allow Item Interface to interface with more items

### ISSUE THREAD

**Issue by c0ldk453** [CJ-MC-Mods/IBHSTD#66]
I'm talking some simple things like acting as a chest when a bag/backpack/alchemical bag is put into it.  Or having a face where it "right-clicks" with the item inside it when it's something like a sword or wand.  At the moment, it just feels like an item charger.  Not an interface.

**Comment by cjm721** [comment]
If it doesn't behave like a chest when you put a bag in that's the fault of that mods bags. 

The way it works already exposes all capabilities of the item so a if something does not behave as expected that's on that item.

One exception to that is if it's capabilities only are on the top/bottom side of the item, of which I will be adding something to get around that probably in next MC version.



As for right clicking using the item, that's not a thing items do. That is a property of an entity. Also it already exists in Overloaded as the item manipulator. It is just currently in the dev item mode so it doesn't show up unless the config turns it on.
