### ISSUE TITLE
Infinity Tank not working with normal extraction mechanisms

### ISSUE THREAD

**Issue by resinate** [CJ-MC-Mods/IBHSTD#71]
how do we extract stuff from liquid block, im able to store liquids but im not able to extract them???

from what ive seen this mod ONLY accepts manual buckets? is this mod not good with any fluid pipes of any mod to extract the fluid in the block?

seems you tried to patch a bug with issue #69 but turned out u shut off entire tank for good lol so it a way its one giant trash can lol

https://cdn.discordapp.com/attachments/518004694681911299/593046751611453483/unknown.png

**Comment by TeetoKaziim** [comment]
None of these mods extraction methods seem to work:
Extra Utilities Fluid Transfer Nodes
Ender IO Ender Fluid Conduits
Thermal Dynamics Servo on a Super Laminar Fluidduct
Xnet Fluid Channel

Fluid can be inserted into the first Infinity Tank, and accumulates there, but cannot be pulled out.
Similarly, the infinity capacitor seems unable to have power extracted from it using any of these mods power cables:

![image](https://user-images.githubusercontent.com/25490944/60099095-98350200-971c-11e9-8563-61b88deda2f7.png)

Substituting in a more mundane capacitor or tank where the infinity capacitors are immediately results in power/fluid being transfered:

![image](https://user-images.githubusercontent.com/25490944/60099253-e64a0580-971c-11e9-98ce-08c289a2636c.png)

EDIT: A link to my modlist for these tests:
https://gist.github.com/TeetoKaziim/9c96e6dea75647815340ace175ac0d2c

**Comment by TeetoKaziim** [comment]
I was just reminded that <https://github.com/CJ-MC-Mods/Overloaded/wiki/Energy-Extractor> exists for the energy storage infinity capacitor and now I look like a dumb.

Do not adjust your monitor: I AM a dumb, sometimes.

**Comment by cjm721** [comment]
Will look into the Infinity Tank later today, have a guess as to what is causing it.

Does it pull out if you set a filter on what you are using to pull out?

**Comment by resinate** [comment]
nope nothing what u could do is make same block u did for energy extraction for fluid call it good lol
also was curious which value is longer LONG or DOUBLE? which ever one is bigger we should use it lol

**Comment by cjm721** [comment]
I just fixed it to work like a normal tank, no need for a fluid extractor. Only reason there is an energy one is because the way forge designed the API is not efficient and by having the extractor got around some of the issues.

And on long vs double: double is larger and no I won't use it as it would allow duping and has many other issues.

**Comment by resinate** [comment]
how could u dupe? what if u used a special block like energy extractor?

**Comment by cjm721** [comment]
I am not changing how the current Infinity containers work and they will not be increasing their storage amount. I am making larger containers but that is for a later date and will be different blocks.

As for duping read: https://en.wikipedia.org/wiki/Floating_point_error_mitigation
