### ISSUE TITLE
Crash to desktop in loading Overloaded-1.14.3-0.0.63 

### ISSUE THREAD

**Issue by IchigoGames** [CJ-MC-Mods/IBHSTD#75]
#### Overloaded Version: Overloaded-1.14.3-0.0.63 
forge-1.14.3-27.0.47 and 27.0.43
after updating mod with no changes to config i crashed crashed
[crash-2019-07-10_10.22.13-client.txt](https://github.com/CJ-MC-Mods/Overloaded/files/3378238/crash-2019-07-10_10.22.13-client.txt)
also try to change max texture size to something lower to see if that was the issue but it
did not work it still crashed. this is a crash to desktop in loading screen. and did not happen in overloaded 62

**Comment by cjm721** [comment]
Update your forge to at least version 23
