### ISSUE TITLE
Error during Common_Event Setup Phase

### ISSUE THREAD

**Issue by wulfenbach-jpg** [CJ-MC-Mods/IBHSTD#78]
#### Overloaded Version: 0.0.70
After updating to Forge 28.0.45, when loading up Minecraft, this mod gives me an error message, "overloaded encountered an error during the common_event setup phase."
Here are the debug and latest logs.
[debug.log](https://github.com/CJ-MC-Mods/Overloaded/files/3473465/debug.log)
[latest.log](https://github.com/CJ-MC-Mods/Overloaded/files/3473467/latest.log)

**Comment by cjm721** [comment]
Overloaded is not compatible with forge over 43

**Comment by cjm721** [comment]
Overloaded is not compatible with forge over 43
