### ISSUE TITLE
imagingOpException startup crash

### ISSUE THREAD

**Issue by readalot** [CJ-MC-Mods/IBHSTD#79]
1.12.2
overloaded-1.12.2-0.0.58
Dungeons and Dragons and Spaceships crash on startup
java.awt.image.ImagingOpException: Unable to transform src image

I keep getting a crash when trying to start this modpack, I have tried lessening ram & giving it more but I'm not very good at figuring this sort of thing out. I would really REALLY appreciate some assistance my dad and I wanted to play this together
https://paste.dimdev.org/bocunizohu.mccrash

**Comment by cjm721** [comment]
Primary guess is you need to use a more up-to-date version of Java. That crash log says you on 8.51 and current version is above 200. Low versions of java 8 changed the image library quite a bit.
