### ISSUE TITLE
Multi armor config

### ISSUE THREAD

**Issue by WarpDarkmatter** [CJ-MC-Mods/IBHSTD#80]
#### Overloaded Version: 0.0.58
I know there is a way to configure the speed and whatnot of the multi armor, but I can't find what I need to do to open the config for that, I've tried crouch-clicking, going into the mod config, going into the keybinds and searching everything that could possibly come to mind for the key, I looked at the wiki, reddit, and I still can't find anything that tells me how to open the config. here is where I found the config open: https://www.reddit.com/r/feedthebeast/comments/ap0t6b/po3multi_armor_is_a_just_a_bit_op/

**Comment by cjm721** [comment]
Need the Settings Editor item and right click with it. (In the video its in his hand)
