### ISSUE TITLE
Healer on Multi Armor Set "hurting the player"

### ISSUE THREAD

**Issue by Munster08** [CJ-MC-Mods/IBHSTD#81]
#### Overloaded Version: 0.0.58

Issue: When player has Full set of Multi Armor with the function of the Healer set to True the player will heal instantly than proceed to take Damage causing screen shake and player redness, this can be stopped if the player disables the Healer.

**Comment by cjm721** [comment]
This does not happen with just Overloaded installed, need more information.

**Comment by Munster08** [comment]
Well i have Heart containers from Cyclic magic, thats the only thing that adds to my health, would that be the problem??

**Comment by cjm721** [comment]
Can you test with just that mod plus overloaded and find out.

**Comment by Munster08** [comment]
seems to be fine in Single player, i forgot to add that this bug is on a multiplayer server, also the hearts instead of going above the base hearts change the color of the heart on the MP server. would there be a issue where the game thinks i'm " hacking" therefore making my health try to go back down?

**Comment by cjm721** [comment]
Can you recreate on a server with just those two mods.

**Comment by Munster08** [comment]
I will test everything i can and i will get back to you asap.

**Comment by cjm721** [comment]
As been a month, closing. Re-open if you replicate it.
