### ISSUE TITLE
Energy transfer / storage

### ISSUE THREAD

**Issue by MUHAKLorTheDorfTrottel4Github** [CJ-MC-Mods/IBHSTD#93]
mc 1.15.2
forge-1.15.2-31.1.12
Overloaded-1.15.2-0.0.84

?   is the energy transfer/storage working at all in 1.15.2

if so, how to get it to run

energy sender will not drain power from energy cubes
energy extractor will not drain power from energy cubes
sender receiver can be linked usind linking tool 
capacitor do not connect to universal cable 

IS THE WIKI FROM 4/2017 STILL VALID

anybody out there who solved WHOW ( 1.15.2)

regards

**Comment by cjm721** [comment]
Everything is working correctly for me. Wiki is still basically up to date except the *True* blocks are new and only interact with their hyper counterparts.

Power goes from left to right.
![image](https://user-images.githubusercontent.com/2738614/75088481-7f2a5e00-5502-11ea-9fe0-f5762c376fd3.png)

**Comment by MUHAKLorTheDorfTrottel4Github** [comment]
thx for the quick answer

i tried with most left block a charged mekanism Ultimate energy cube,
set all output, eject yes, next to it a true infinity capacitor

the capacitor do not accept energy and the cube is not draining.
Mekanism-1.15.2-9.9.10.402

what is the most left block on your setting?

regards

**Comment by cjm721** [comment]
True blocks only interact with their hyper counterparts. You cannot put into or take out of them via normal means.

The green one on the left is an almost infinite capacitor.
