### ISSUE TITLE
ENERGY STORAGE (again)

### ISSUE THREAD

**Issue by MUHAKLorTheDorfTrottel4Github** [CJ-MC-Mods/IBHSTD#94]
mc 1.15.2
forge-1.15.2-31.1.16
Overloaded-1.15.2-0.0.85
-------------------------------------------------------
almost infinity storage:
does report rf amount to chat
does not report percentage to chat , always 0.0000
but:
max Rf should 2^31 = 2.147.483.648 should 100%

I'm feeding with 4mill/rf/tick ( 4 x maxed Mek,Reactor)
currently (almost infinity storage) : 
2.181.800.000 rf ( chat) , 508 %  ( by rftools information screen or enegy module/screen)
--------------------------------------------------
true infinite storage 
does report RF amout to screen and ?bit?
does not report percentage to chat
does not provide any information to rf Readers ( like rftools information sceen )
-------------------------------------
is it possible to create a "super energy cable" which transfer more than just 200k/tick
( i'm running out of ports on mek.reactor, like to have 1 instead of 5 for energy out) 
----------------------------------------------
regards

**Comment by cjm721** [comment]
https://github.com/CJ-MC-Mods/Overloaded/wiki/Infinity-Storage

Just takes a lot of power to move it (it actually prints out ratio of 1 so its percent is current value multiplied by 100, guess I'll fix that): 
![image](https://user-images.githubusercontent.com/2738614/75524079-0c1d5d80-59c2-11ea-8f6c-d2d5a599b23a.png)


True Infinity Capacitor can hold 2^(2^31) (a number 646,456,994 decimal digits long). The bits is the actual amount of memory space it takes to hold that number.

**Comment by cjm721** [comment]
Also for moving large amounts around: https://github.com/CJ-MC-Mods/Overloaded/wiki/Hyper-Transfer
