### ISSUE TITLE
Player Interface with Hopper results in item duplication

### ISSUE THREAD

**Issue by James103** [CJ-MC-Mods/IBHSTD#98]
#### Overloaded Version: 0.0.59

By using a Hopper and a Player Interface, it is possible to duplicate items.

Steps to Reproduce:
1. Place a rail, then place a player interface on top of the rail.
2. Place a Minecart Hopper.
3. Place two item types in the hopper.
4. Rapidly shift-click out of the hopper.
5. Items will be duplicated.
6. Close the container, and open your inventory. The duplicated items become real.

**Comment by cjm721** [comment]
Unable to replicate, did get visual de-synced for a bit but soon as refresh happened extra items disappeared.

Going to need to see an actual example of this happening that is not a visual de-sync.
